# Generated by Django 3.1.14 on 2022-08-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=240)),
                ('old', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
    ]
