# Generated by Django 3.1.14 on 2022-09-27 08:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'name': 'mamoru'}),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='mamoru@gmail.com', max_length=240),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='mamoru', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='old',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(default='mamoru', max_length=10),
        ),
    ]
