# Generated by Django 4.1.2 on 2022-10-11 03:22

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('google_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='calendar_list',
        ),
        migrations.AddField(
            model_name='user',
            name='calendarlist',
            field=django_mysql.models.ListCharField(models.CharField(max_length=15), default=['mamoru'], max_length=165, size=10),
            preserve_default=False,
        ),
    ]
