# Generated by Django 4.1.2 on 2022-10-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_app', '0002_remove_user_calendar_list_user_calendarlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='calendarlist',
        ),
        migrations.AddField(
            model_name='user',
            name='datalist',
            field=models.JSONField(default={'list': ['list']}),
        ),
    ]
