# Generated by Django 4.1.2 on 2022-10-14 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('google_app', '0004_lifeexpectancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.IntegerField(default=0)),
                ('sex', models.CharField(default='mamoru', max_length=10)),
                ('data', models.JSONField(default={'name': 'mamoru'})),
                ('datalist', models.JSONField(default={'list': ['list']})),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
