# Generated by Django 3.2.16 on 2022-10-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_app', '0005_accounts_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='account_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='sex',
            field=models.IntegerField(choices=[(1, '男性'), (2, '女性'), (3, 'Xジェンダー')]),
        ),
    ]
